# so this will define error codes for better maintenance
SHORT_USERNAME = 5
USERNAME_NOT_FOUND = 2
PASSWORD_NOT_FOUND = 3
EMAIL_NOT_FOUND = 4
WRONG_EMAIL = 1
ALREADY_REGISTERED_USERNAME = 6
USERNAME_AVAIL = 7
EMAIL_NON_VALID = 8
ALREADY_REGISTERED_EMAIL = 9
EMAIL_AVAIL = 10
USED_USERNAME = 11
WRONG_LOGIN = 12
